debug=true
oauth.consumerKey=mFSTmCgYpkJOHgxOBvXwUKd9e
oauth.consumerSecret=yKVRlXhoOfpxnEDZiXXEG6utoucxaFfOg3iZT7KjHNgNG1WCtX
oauth.accessToken=1526031953949913088-pa3l7qOLn3mxC6u9PgmVuA2VJFIZb2
oauth.accessTokenSecret=5MXnPDeZN6vKQ2TIGADgusQrCHc5GOuKvrqDO83bS96jw