debug=false
oauth.consumerKey=Wc92XMzIp7si83vdXUKl43Oa4
oauth.consumerSecret=DpoLx4imLFoT6ZgSpB52CKRnxrXGGlpZWGMQMBWMJpRHEzixDz
oauth.accessToken=1526031953949913088-dkW5JN6ShCVaakGwMgGv4hqZDMLPC7
oauth.accessTokenSecret=Q9Z8pTOtmbzGl3KvsaxgX2rFsr8neplkwv0zxmHyZcceX